
server:
  port: 8083
spring:
 data:
   mongodb:
     uri: mongodb+srv://demo:<password>@cluster0.nresu.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
 application:
   name: room-service
eureka:
 instance:
   hostname: localhost

